[package]
name = "mdbook-frntmtr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.15"
regex = "1.5.4"
clap = "3.0.10"
semver = "1.0.4"
serde_json = "1.0.78"

