name: Build tools binary and save
on: 
  workflow_dispatch:

jobs:
  build-binary:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          cargo install mdbook
          cargo install --git https://github.com/kkibria/mdbook-frntmtr.git

      - name: zip for .github/ubuntu # we have to manually copy the zip file
      - uses: actions/upload-artifact@v2
        with:
          name: tools-binary
          path: ~/.cargo/bin/mdbook*